version: '3.8'

services:

  vllm_server:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_API_KEY}
      - MODEL_NAME=${MODEL_NAME}

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: >
      --model ${MODEL_NAME}
      --gpu-memory-utilization 0.90
      --max-model-len 8192
      --kv-cache-dtype auto
      --max-num-seqs 128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]




  keycloak:
      image: my-keycloak-image
      build:
        context: .
        dockerfile: DockerKeykloack
      ports:
        - "9080:9080"
      environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
        KC_DB_USERNAME: keycloak_user
        KC_DB_PASSWORD: keycloak_password
        JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
        JGROUPS_DISCOVERY_PROPERTIES: "initialize_sql=CREATE TABLE IF NOT EXISTS JGROUPS_PING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data bytea DEFAULT NULL, added timestamp DEFAULT NOW(), PRIMARY KEY (own_addr, cluster_name))"
      depends_on:
        - postgres
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak_db


  # Optimize with CUDA 
  test_vllm:
    restart: always  # ou restart: unless-stopped
    runtime: nvidia
    build:
      context: .
      dockerfile: DockerfileRun
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      # - //c/Users/pc/Desktop/gcp/local-llm/model:/model
      - //c/Users/julie/Desktop/gcloudllm/CloudRun-LLM/model:/model
      # - //d/models:/model
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
        # limits:
        #   cpus: '12.0'  # L'i9-14700KF a 20 cœurs, on en utilise 12
        #   memory: 48G   # Limite à 48 Go de RAM
        # reservations:
        #   cpus: '8.0'   # Réserve au moins 8 cœurs
        #   memory: 32G   # Réserve au moins 32 Go de RAM
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]



 # Nouveau service PostHog
  posthog:
    image: posthog/posthog:latest
    restart: always
    ports:
      - "8003:8000"
    volumes:
      - posthog-data:/data
    env_file:
      - .env

  clickhouse:
    image: yandex/clickhouse-server:latest
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9440:9440"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server/config.d/ # Si vous utilisez un répertoire pour plusieurs fichiers de config

  redis:
      image: redis:6.2-alpine
      restart: always
      ports:
        - "6379:6379"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posthog





  
  # Optimize with CUDA 
  test_parallele:
    runtime: nvidia
    build:
      context: .
      dockerfile: DockerfileParallele
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - VLLM_TRACING=1  # Activer le tracing
      - VLLM_PROFILING=1  # Profilage des performances
      - CUDA_LAUNCH_BLOCKING=1  # Debug CUDA
      - PYTHONASYNCIODEBUG=1  # Debug asyncio
    volumes:
      - //c/Users/julie/Desktop/gcloudllm/CloudRun-LLM/model:/model
      # - //d/models:/model
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
        # limits:
        #   cpus: '12.0'  # L'i9-14700KF a 20 cœurs, on en utilise 12
        #   memory: 48G   # Limite à 48 Go de RAM
        # reservations:
        #   cpus: '8.0'   # Réserve au moins 8 cœurs
        #   memory: 32G   # Réserve au moins 32 Go de RAM
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  # myapp:
  #   build:
  #     context: .
  #     dockerfile: DockerfileLocal
  #   env_file:
  #     - .env
  #   volumes:
  #     - //c/Users/pc/Desktop/gcp/local-llm/model:/model
  #   ports:
  #     - "${PORT}:${PORT}"

  #   deploy:
  #      resources:
  #        reservations:
  #          devices:
  #            - driver: nvidia
  #              count: all
  #              capabilities: [gpu]

    # depends_on:
    #   - vllm_server

volumes:
  pg-data:
  model_data:
  posthog-data:
  clickhouse-data:
  clickhouse-config: